GET http://localhost:5000/productstwo
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA2NjIyODAsImV4cCI6MTY1MDY2MjMwMCwiYXVkIjoiNjI1ZGI3YmE3M2FiNTU2Y2ExZjQyMzNhIn0.wSzowhzfDAWq-JEiffMP3qFBmlbzqrMrkPcMXbpePdM

###

GET http://localhost:5000/